version: '3.8'
services:
  api:
    build:
      context: "./"
      dockerfile: "Dockerfile.dev"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=dev
      - PORT=5000
    ports:
      - '127.0.0.3:5000:5000'
    working_dir: /root/app
    volumes:
      - ./:/root/app:cached 
      
  # apiprod:
  #   build:
  #     context: "./"
  #     dockerfile: "Dockerfile.prod"
  #   command: sh -c "npm install --prod && npm run start:prod"  
  #   environment:
  #     - NODE_ENV=prod
  #     - PORT=3467
  #   ports:
  #     - '127.0.0.5:3467:3467'
  #   volumes:
  #     - ./:/app:cached 
    